### ISSUE TITLE
Duplicate files in parts

### ISSUE THREAD

**Issue by guysoft** [apollo-ng/seedstack#1]
Hey,
What is the difference between these two files in the repo?:
https://github.com/apollo-ng/seedstack/blob/master/parts/seedstack-container-1.stl

https://github.com/apollo-ng/seedstack/blob/master/parts/seedstack-container.stl

**Comment by chron0** [comment]
Ah, sweet, github also has a STL viewer built-in, learned something new :) The difference is the width of the sidewalls. When you observe both objects closely, you'll see, that -1 has a slightly thicker wall. This gives the wall a bit more stability but was actually a hack, so that the slicer would not try to lay two outer shells and infill (which causes a lot of vibrations) but lay just 4 outer shells (two outside and two on the inside) without any additional infill (faster and higher quality print). That's why it's important to have the source files for our projects available, so you can customize this according to your print setup.

**Comment by guysoft** [comment]
Ok, assuming your printer is also with a 400 micron nozzle then its optimized for that wall width.
I will try and print it here, and I have a friend that has been sprouting for a while, I hope we could generate insight from that.

**Comment by chron0** [comment]
The nozzle of our printer (https://apollo.open-resource.org/mission:resources:picoprint) has 0.35. Just run it through your slicer and see how it behaves in simulation, you could also use our slic3r configs as a start: https://github.com/apollo-ng/seedstack/tree/master/config

If you generate any insights, please be kind enough to document and share it, so that we all can benefit from the knowledge that we generate collectively. Also, according to what I've read it seems to be favorable for the sprouts not only to be in the dark, but to actually have pressure applied to them. That's why there already are slots in the sidewalls of the container. They can be used to print and slide in section walls, in order to try smaller harvest volumes of different seeds in the same container or use these slots to guide a mesh like object (also printed) that would be put on top of the seeds, so that they have to work to push it up in order to give them room to grow. This is supposed to yield thicker sprouts, so I think it's worthwhile testing.

**Comment by guysoft** [comment]
Ok all parts printers, using a 400mm nozzle BQ Prusa i3 Hephestos.
Container is water tight.

Question off topic: did you keep adding water to the stack? If so how often?
